name: template
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.1+2

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  auto_route: ^5.0.1
  autoequal: ^0.4.0
  copy_with_extension: ^4.0.0
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  dio: ^4.0.6
  json_annotation: ^4.7.0
  keyboard_dismisser: ^3.0.0
  searchfield: ^0.7.1
  flutter_svg: ^1.1.5
  fl_chart: ^0.55.2
  intl: ^0.17.0
  r_dotted_line_border: ^0.1.1

dev_dependencies:
  auto_route_generator: ^5.0.2
  autoequal_gen: ^0.4.0
  bloc_test: ^9.0.2
  build_runner: ^2.1.7
  copy_with_extension_gen: ^4.0.1
  flutter_lints: ^2.0.1
  flutter_native_splash: ^2.0.5
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  json_serializable: ^6.5.3

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/illustrations/
